// src/rules/no-react-specific-props/rule.ts
import { ESLintUtils } from '@typescript-eslint/utils';
import type { TSESLint } from '@typescript-eslint/utils';
import { isDOMElementName, jsxGetProp, jsxHasProp } from '../../utils.js';

const createRule = ESLintUtils.RuleCreator.withoutDocs;

const reactSpecificProps = [
  { from: 'className', to: 'class' },
  { from: 'htmlFor', to: 'for' },
];

export default createRule({
  meta: {
    type: 'problem',
    docs: {
      description:
        'Disallow usage of React-specific `className`/`htmlFor` props, which were deprecated in v1.4.0.',
      url: 'https://github.com/iamssen/eslint-plugin-solid/blob/main/src/rules/no-react-specific-props/readme.md',
    },
    fixable: 'code',
    schema: [],
    messages: {
      prefer:
        'Prefer the `{{ to }}` prop over the deprecated `{{ from }}` prop.',
      noUselessKey:
        'Elements in a <For> or <Index> list do not need a key prop.',
    },
  },
  // defaultOptions: [],
  create(context) {
    return {
      JSXOpeningElement(node) {
        for (const { from, to } of reactSpecificProps) {
          const classNameAttribute = jsxGetProp(node.attributes, from);
          if (classNameAttribute) {
            // only auto-fix if there is no class prop defined
            const fix = !jsxHasProp(node.attributes, to)
              ? (fixer: TSESLint.RuleFixer) =>
                  fixer.replaceText(classNameAttribute.name, to)
              : undefined;

            context.report({
              node: classNameAttribute,
              messageId: 'prefer',
              data: { from, to },
              fix,
            });
          }
        }
        if (
          node.name.type === 'JSXIdentifier' &&
          isDOMElementName(node.name.name)
        ) {
          const keyProp = jsxGetProp(node.attributes, 'key');
          if (keyProp) {
            // no DOM element has a 'key' prop, so we can assert that this is a holdover from React.
            context.report({
              node: keyProp,
              messageId: 'noUselessKey',
              fix: (fixer) => fixer.remove(keyProp),
            });
          }
        }
      },
    };
  },
});

// src/rules/no-react-deps/rule.ts
import { ESLintUtils } from '@typescript-eslint/utils';
import { isFunctionNode, trace, trackImports } from '../../utils.js';

const createRule = ESLintUtils.RuleCreator.withoutDocs;

export default createRule({
  meta: {
    type: 'problem',
    docs: {
      description:
        'Disallow usage of dependency arrays in `createEffect` and `createMemo`.',
      url: 'https://github.com/iamssen/eslint-plugin-solid/blob/main/src/rules/no-react-deps/readme.md',
    },
    fixable: 'code',
    schema: [],
    messages: {
      noUselessDep:
        "In Solid, `{{name}}` doesn't accept a dependency array because it automatically tracks its dependencies. If you really need to override the list of dependencies, use `on`.",
    },
  },
  // defaultOptions: [],
  create(context) {
    /** Tracks imports from 'solid-js', handling aliases. */
    const { matchImport, handleImportDeclaration } = trackImports();

    return {
      ImportDeclaration: handleImportDeclaration,
      CallExpression(node) {
        if (
          !(
            node.callee.type === 'Identifier' &&
            matchImport(['createEffect', 'createMemo'], node.callee.name) &&
            node.arguments.length === 2 &&
            node.arguments.every((arg) => arg.type !== 'SpreadElement')
          )
        ) {
          return;
        }

        // grab both arguments, tracing any variables to their actual values if possible
        const [arg0, arg1] = node.arguments.map((arg) => trace(arg, context));

        if (
          isFunctionNode(arg0) &&
          arg0.params.length === 0 &&
          arg1.type === 'ArrayExpression'
        ) {
          // A second argument that looks like a dependency array was passed to
          // createEffect/createMemo, and the inline function doesn't accept a parameter, so it
          // can't just be an initial value.
          context.report({
            node: node.arguments[1], // if this is a variable, highlight the usage, not the initialization
            messageId: 'noUselessDep',
            data: {
              name: node.callee.name,
            },
            // remove dep array if it's given inline, otherwise don't fix
            fix:
              arg1 === node.arguments[1]
                ? (fixer) => fixer.remove(arg1)
                : undefined,
          });
        }
      },
    };
  },
});
